logging:
  level:
    cce: INFO
    org:
      springframework:
        ws: DEBUG
client.ssl.trust-store: classpath:truststore.jks
client.ssl.trust-store-password: changeit
client.ssl.key-store: jems-client.jks
client.ssl.key-store-alias: client
client.ssl.key-store-password: changeit
client.ws:
  url: 'https://ws.jnet.beta.pa.gov/AOPC/CCERequest'
  reply: 'https://uat.captorapi.cor.state.pa.us/cce/CCEReply.svc'
  user: 'test.user'
  trackingId: 'T4504835'
  docketId: 'CP-25-CR-0002884-2016'