logging:
  level:
    cce: INFO
    org:
      springframework:
        ws: DEBUG
client.ssl.trust-store: classpath:truststore.jks
client.ssl.trust-store-password: changeit
client.ssl.key-store: jems-client.jks
client.ssl.key-store-password: changeit
client.ws-url: 'https://ws.jnet.beta.pa.gov/AOPC/CCERequest'