//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.05.13 at 09:51:38 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://niem.gov/niem/niem-core/2.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cce.client;
